version: '3.0'
services:
  web:
    build: .
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app/
    ports:
      - "5000:5000"
    depends_on:
      - mysql
   
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-volume/mysql-data:/var/lib/mysql
